---
- name: include os variables
  include_vars: "{{git_os}}.yml"
  when: git_os is defined and git_os != ""

################################################################################################

- name: install git
  apt: pkg={{git_package}} state=present update_cache=yes cache_valid_time=3600